// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownLintVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "MarkdownLintVS.86d3a7c7-0313-4f57-ad29-3cb41e022405";
        public const string Name = "Markdown Lint";
        public const string Description = @"Markdown linting extension for Visual Studio. Provides lint warnings and errors for markdown files based on markdownlint rules (MD001-MD058). Configure rules via .editorconfig files.";
        public const string Language = "en-US";
        public const string Version = "1.0.900";
        public const string Author = "Mads Kristensen";
        public const string Tags = "markdown,lint,linting,md,documentation";
        public const bool IsPreview = false;
    }
}
