// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MarkdownLintVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MarkdownLintVSString = "885a2d95-251c-4eb2-9b74-5c05c87bc9dd";
        public static Guid MarkdownLintVS = new Guid(MarkdownLintVSString);

        public const string MarkdownFileOpenString = "a9b85cb7-4e4c-4f7c-9e1a-2d3c5e7f1a2b";
        public static Guid MarkdownFileOpen = new Guid(MarkdownFileOpenString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorContextMenuGroup = 0x0001;
        public const int FlyoutMenu = 0x0010;
        public const int FlyoutEnabledGroup = 0x0011;
        public const int FlyoutSettingsGroup = 0x0012;
        public const int SolutionExplorerFolderGroup = 0x0020;
        public const int SolutionExplorerProjectGroup = 0x0021;
        public const int SolutionExplorerSolutionGroup = 0x0022;
        public const int WorkspaceContextMenuGroup = 0x0023;
        public const int ErrorListContextMenuGroup = 0x0024;
        public const int EnabledCommand = 0x0100;
        public const int SettingsCommand = 0x0101;
        public const int LintFolderCommand = 0x0102;
        public const int LintProjectCommand = 0x0103;
        public const int LintSolutionCommand = 0x0104;
        public const int LintOpenFolderCommand = 0x0105;
        public const int SuppressInCodeCommand = 0x0106;
        public const int idmWSE_ContextMenu = 0x0002;
    }
}
